#
# Autogenerated by Thrift Compiler (1.0.0-dev)
#
# DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
#

require 'thrift'
require 'user_service_types'

module UserService
  class Client
    include ::Thrift::Client

    def getName()
      send_getName()
      return recv_getName()
    end

    def send_getName()
      send_message('getName', GetName_args)
    end

    def recv_getName()
      result = receive_message(GetName_result)
      return result.success unless result.success.nil?
      raise ::Thrift::ApplicationException.new(::Thrift::ApplicationException::MISSING_RESULT, 'getName failed: unknown result')
    end

  end

  class Processor
    include ::Thrift::Processor

    def process_getName(seqid, iprot, oprot)
      args = read_args(iprot, GetName_args)
      result = GetName_result.new()
      result.success = @handler.getName()
      write_result(result, oprot, 'getName', seqid)
    end

  end

  # HELPER FUNCTIONS AND STRUCTURES

  class GetName_args
    include ::Thrift::Struct, ::Thrift::Struct_Union

    FIELDS = {

    }

    def struct_fields; FIELDS; end

    def validate
    end

    ::Thrift::Struct.generate_accessors self
  end

  class GetName_result
    include ::Thrift::Struct, ::Thrift::Struct_Union
    SUCCESS = 0

    FIELDS = {
      SUCCESS => {:type => ::Thrift::Types::STRING, :name => 'success'}
    }

    def struct_fields; FIELDS; end

    def validate
    end

    ::Thrift::Struct.generate_accessors self
  end

end

